################### 本地环境 数据库相关配置 ###################
configs:
  datasource:
    ################### 案例展示模块 ###################
    platform-demo:
      database: platform-demo
      address: rm-2ze3so3bq100b92u62o.mysql.rds.aliyuncs.com
      username: daixu
      password: Aa123456!
    ################### 用户模块 ###################
    platform-user:
      database: platform-user
      address: rm-2ze3so3bq100b92u62o.mysql.rds.aliyuncs.com
      username: daixu
      password: Aa123456!
